// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv3NGqLSYhuASDgc_qB7MzWbM_-XcMwbE',
    appId: '1:819007775521:web:2686803ce85c6e8e2fd460',
    messagingSenderId: '819007775521',
    projectId: 'myfirebase-78309',
    authDomain: 'myfirebase-78309.firebaseapp.com',
    storageBucket: 'myfirebase-78309.appspot.com',
    measurementId: 'G-H4BDHJPYRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysaa-cwMvoIAGNCdTrsufNPbBYPp9n5A',
    appId: '1:819007775521:android:c37c4cc25f3211112fd460',
    messagingSenderId: '819007775521',
    projectId: 'myfirebase-78309',
    storageBucket: 'myfirebase-78309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfiUbpl_mReUlgtaHbut2l_wnndNN86Yo',
    appId: '1:819007775521:ios:7a17f14565144cb92fd460',
    messagingSenderId: '819007775521',
    projectId: 'myfirebase-78309',
    storageBucket: 'myfirebase-78309.appspot.com',
    iosClientId: '819007775521-vdskdpipldpc79aevld140nmudd4vdp2.apps.googleusercontent.com',
    iosBundleId: 'mijeong.myDtabase',
  );
}
